# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'error_report_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_error_Dialog(object):
    def setupUi(self, error_Dialog):
        error_Dialog.setObjectName("error_Dialog")
        error_Dialog.setEnabled(True)
        error_Dialog.resize(696, 700)
        error_Dialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.gridLayout_2 = QtWidgets.QGridLayout(error_Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(error_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.error_path_label = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.error_path_label.sizePolicy().hasHeightForWidth())
        self.error_path_label.setSizePolicy(sizePolicy)
        self.error_path_label.setObjectName("error_path_label")
        self.error_path_previous_pushButton = QtWidgets.QPushButton(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.error_path_previous_pushButton.sizePolicy().hasHeightForWidth())
        self.error_path_previous_pushButton.setSizePolicy(sizePolicy)
        self.error_path_previous_pushButton.setObjectName("error_path_previous_pushButton")
        self.error_path_next_pushButton = QtWidgets.QPushButton(self.splitter)
        self.error_path_next_pushButton.setObjectName("error_path_next_pushButton")
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.error_path_comboBox = QtWidgets.QComboBox(error_Dialog)
        self.error_path_comboBox.setEnabled(True)
        self.error_path_comboBox.setObjectName("error_path_comboBox")
        self.gridLayout.addWidget(self.error_path_comboBox, 1, 0, 1, 1)
        self.error_log_textBrowser = QtWidgets.QTextBrowser(error_Dialog)
        self.error_log_textBrowser.setObjectName("error_log_textBrowser")
        self.gridLayout.addWidget(self.error_log_textBrowser, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.error_close_pushButton = QtWidgets.QPushButton(error_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.error_close_pushButton.sizePolicy().hasHeightForWidth())
        self.error_close_pushButton.setSizePolicy(sizePolicy)
        self.error_close_pushButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.error_close_pushButton.setObjectName("error_close_pushButton")
        self.gridLayout_2.addWidget(self.error_close_pushButton, 1, 0, 1, 1)

        self.retranslateUi(error_Dialog)
        QtCore.QMetaObject.connectSlotsByName(error_Dialog)

    def retranslateUi(self, error_Dialog):
        _translate = QtCore.QCoreApplication.translate
        error_Dialog.setWindowTitle(_translate("error_Dialog", "Error Report"))
        self.error_path_label.setText(_translate("error_Dialog", "Error path"))
        self.error_path_previous_pushButton.setText(_translate("error_Dialog", "<"))
        self.error_path_next_pushButton.setText(_translate("error_Dialog", ">"))
        self.error_close_pushButton.setText(_translate("error_Dialog", "Close"))
