# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'progress_window_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_progress_window(object):
    def setupUi(self, Dialog_progress_window):
        Dialog_progress_window.setObjectName("Dialog_progress_window")
        Dialog_progress_window.setWindowModality(QtCore.Qt.WindowModal)
        Dialog_progress_window.resize(340, 203)
        Dialog_progress_window.setWindowTitle("Processing")
        Dialog_progress_window.setLayoutDirection(QtCore.Qt.LeftToRight)
        Dialog_progress_window.setSizeGripEnabled(False)
        self.gridLayout = QtWidgets.QGridLayout(Dialog_progress_window)
        self.gridLayout.setObjectName("gridLayout")
        self.label_state_progress = QtWidgets.QLabel(Dialog_progress_window)
        self.label_state_progress.setStyleSheet("font: 12pt \"Arial\";")
        self.label_state_progress.setObjectName("label_state_progress")
        self.gridLayout.addWidget(self.label_state_progress, 0, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(Dialog_progress_window)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 1, 0, 1, 1)
        self.pushButton_cancel = QtWidgets.QPushButton(Dialog_progress_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_cancel.sizePolicy().hasHeightForWidth())
        self.pushButton_cancel.setSizePolicy(sizePolicy)
        self.pushButton_cancel.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.gridLayout.addWidget(self.pushButton_cancel, 2, 0, 1, 1)

        self.retranslateUi(Dialog_progress_window)
        QtCore.QMetaObject.connectSlotsByName(Dialog_progress_window)

    def retranslateUi(self, Dialog_progress_window):
        _translate = QtCore.QCoreApplication.translate
        self.label_state_progress.setText(_translate("Dialog_progress_window", "Running......"))
        self.pushButton_cancel.setText(_translate("Dialog_progress_window", "Cancel"))
