# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choose_ref_ligand_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_pick_ref_ligand(object):
    def setupUi(self, Dialog_pick_ref_ligand):
        Dialog_pick_ref_ligand.setObjectName("Dialog_pick_ref_ligand")
        Dialog_pick_ref_ligand.setWindowModality(QtCore.Qt.NonModal)
        Dialog_pick_ref_ligand.resize(255, 346)
        Dialog_pick_ref_ligand.setAutoFillBackground(False)
        Dialog_pick_ref_ligand.setSizeGripEnabled(False)
        Dialog_pick_ref_ligand.setModal(False)
        self.gridLayout = QtWidgets.QGridLayout(Dialog_pick_ref_ligand)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget_reflig_list = QtWidgets.QTableWidget(Dialog_pick_ref_ligand)
        self.tableWidget_reflig_list.setObjectName("tableWidget_reflig_list")
        self.tableWidget_reflig_list.setColumnCount(2)
        self.tableWidget_reflig_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_reflig_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_reflig_list.setHorizontalHeaderItem(1, item)
        self.gridLayout.addWidget(self.tableWidget_reflig_list, 0, 0, 1, 3)
        self.pushButton_open = QtWidgets.QPushButton(Dialog_pick_ref_ligand)
        self.pushButton_open.setEnabled(True)
        self.pushButton_open.setObjectName("pushButton_open")
        self.gridLayout.addWidget(self.pushButton_open, 1, 0, 1, 1)
        self.pushButton_confirm = QtWidgets.QPushButton(Dialog_pick_ref_ligand)
        self.pushButton_confirm.setEnabled(True)
        self.pushButton_confirm.setObjectName("pushButton_confirm")
        self.gridLayout.addWidget(self.pushButton_confirm, 1, 1, 1, 1)
        self.pushButton_cancel = QtWidgets.QPushButton(Dialog_pick_ref_ligand)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.gridLayout.addWidget(self.pushButton_cancel, 1, 2, 1, 1)

        self.retranslateUi(Dialog_pick_ref_ligand)
        QtCore.QMetaObject.connectSlotsByName(Dialog_pick_ref_ligand)

    def retranslateUi(self, Dialog_pick_ref_ligand):
        _translate = QtCore.QCoreApplication.translate
        Dialog_pick_ref_ligand.setWindowTitle(_translate("Dialog_pick_ref_ligand", "Choose ref. ligand"))
        item = self.tableWidget_reflig_list.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_pick_ref_ligand", "Ref. Ligands"))
        self.pushButton_open.setText(_translate("Dialog_pick_ref_ligand", "Open"))
        self.pushButton_confirm.setText(_translate("Dialog_pick_ref_ligand", "Confirm"))
        self.pushButton_cancel.setText(_translate("Dialog_pick_ref_ligand", "Cancel"))
