# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'log_viewer_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_log_viewer_Form(object):
    def setupUi(self, log_viewer_Form):
        log_viewer_Form.setObjectName("log_viewer_Form")
        log_viewer_Form.resize(774, 632)
        log_viewer_Form.setLayoutDirection(QtCore.Qt.LeftToRight)
        log_viewer_Form.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.gridLayout = QtWidgets.QGridLayout(log_viewer_Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(log_viewer_Form)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(6)
        self.gridLayout_2.setVerticalSpacing(3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textBrowser.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_2.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.pushButton_close = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_close.sizePolicy().hasHeightForWidth())
        self.pushButton_close.setSizePolicy(sizePolicy)
        self.pushButton_close.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_close.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_close.setObjectName("pushButton_close")
        self.gridLayout_2.addWidget(self.pushButton_close, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(log_viewer_Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(log_viewer_Form)

    def retranslateUi(self, log_viewer_Form):
        _translate = QtCore.QCoreApplication.translate
        log_viewer_Form.setWindowTitle(_translate("log_viewer_Form", "Log Viewer"))
        self.pushButton_close.setText(_translate("log_viewer_Form", "Close"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("log_viewer_Form", "Tab 1"))
