# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_about(object):
    def setupUi(self, Form_about):
        Form_about.setObjectName("Form_about")
        Form_about.resize(1085, 800)
        Form_about.setMaximumSize(QtCore.QSize(1200, 800))
        Form_about.setStyleSheet("background-color: rgb(33, 33, 33);")
        self.gridLayout = QtWidgets.QGridLayout(Form_about)
        self.gridLayout.setObjectName("gridLayout")
        self.textBrowser = QtWidgets.QTextBrowser(Form_about)
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textBrowser.setStyleSheet("background-color: rgb(160, 160, 160);")
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Form_about)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    font: bold 14pt \"微軟正黑體\"; \n"
"    color: rgb(255, 255, 255); /* 文字顏色 */\n"
"    background-color: rgb(60, 60, 60); /* 按鈕背景色 */\n"
"    border-radius: 8px; /* 圓角邊框 */\n"
"    border: 1px solid rgb(80, 80, 80); /* 邊框顏色 */\n"
"    padding: 2px 10px; /* 內距，讓按鈕大小適應內容 */\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(100, 100, 100); /* 滑鼠懸停時變色 */\n"
"    border: 1px solid rgb(120, 120, 120);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(30, 30, 30); /* 按下按鈕時變色 */\n"
"    border: 1px solid rgb(150, 150, 150);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(30, 30, 30); /* 禁用時變色 */\n"
"    color: rgb(120, 120, 120);\n"
"    border: 1px solid rgb(50, 50, 50);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)

        self.retranslateUi(Form_about)
        QtCore.QMetaObject.connectSlotsByName(Form_about)

    def retranslateUi(self, Form_about):
        _translate = QtCore.QCoreApplication.translate
        Form_about.setWindowTitle(_translate("Form_about", "About"))
        self.textBrowser.setHtml(_translate("Form_about", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">MergeonDock is an open-source molecular docking and analysis tool based on </span><span style=\" font-size:16pt; font-weight:600;\">AutoDock 4.2</span><span style=\" font-size:16pt;\"> and </span><span style=\" font-size:16pt; font-weight:600;\">AutoDock Vina</span><span style=\" font-size:16pt;\">,<br />integrating </span><span style=\" font-size:16pt; font-weight:600;\">RDKit</span><span style=\" font-size:16pt;\">, </span><span style=\" font-size:16pt; font-weight:600;\">PyMOL 3.0.0 (Open-Source)</span><span style=\" font-size:16pt;\">, and </span><span style=\" font-size:16pt; font-weight:600;\">Open Babel 3.1</span><span style=\" font-size:16pt;\">.<br />It provides an intuitive </span><span style=\" font-size:16pt; font-weight:600;\">GUI interface</span><span style=\" font-size:16pt;\"> for </span><span style=\" font-size:16pt; font-weight:600;\">protein-ligand docking</span><span style=\" font-size:16pt;\"> and </span><span style=\" font-size:16pt; font-weight:600;\">interaction analysis</span><span style=\" font-size:16pt;\">.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">This software is </span><span style=\" font-size:16pt; font-weight:600;\">fully open-source</span><span style=\" font-size:16pt;\"> under the </span><span style=\" font-size:16pt; font-weight:600;\">MIT License</span><span style=\" font-size:16pt;\">, allowing free use, modification, and distribution.<br />We encourage developers to keep their work open-source and contribute to advancing computational tools in science.</span></p>\n"
"<p style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600;\">📢 Technologies Used</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">MergeonDock utilizes the following open-source technologies:</span></p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-size:16pt;\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://autodock.scripps.edu/\"><span style=\" text-decoration: underline; color:#0000ff;\">AutoDock 4.2</span></a> - Protein-ligand docking calculations</li>\n"
"<li style=\" font-size:16pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://vina.scripps.edu/\"><span style=\" text-decoration: underline; color:#0000ff;\">AutoDock Vina</span></a> - High-performance docking algorithms</li>\n"
"<li style=\" font-size:16pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://www.rdkit.org/\"><span style=\" text-decoration: underline; color:#0000ff;\">RDKit</span></a> - Cheminformatics toolkit</li>\n"
"<li style=\" font-size:16pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://github.com/schrodinger/pymol-open-source\"><span style=\" text-decoration: underline; color:#0000ff;\">PyMOL 3.0.0 (Open-Source)</span></a> - Molecular visualization and analysis</li>\n"
"<li style=\" font-size:16pt;\" style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://openbabel.org/index.html\"><span style=\" text-decoration: underline; color:#0000ff;\">Open Babel 3.1</span></a> - Chemical file format conversion</li></ul>\n"
"<p style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600;\">📜 License Terms</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">MergeonDock is licensed under the </span><span style=\" font-size:16pt; font-weight:600;\">MIT License</span><span style=\" font-size:16pt;\">, which permits </span><span style=\" font-size:16pt; font-weight:600;\">free use, modification, and redistribution</span><span style=\" font-size:16pt;\"><br />while requiring attribution to the original project.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                                                             <img src=\":/images/MergeonDock_sample.png\" />                                 <img src=\":/images/Xhamrock_logo_noback.png\" /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:16pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:16pt;\"><br /></p></body></html>"))
        self.pushButton.setText(_translate("Form_about", "Close"))
from MergeonDock import resources_rc  
